# nginx-proxy/conf.d/justin.kobo-interns.xyz.conf - Without SSL termination
server {
    listen 80;
    server_name justin.kobo-interns.xyz www.justin.kobo-interns.xyz;

    # ACME challenge location for certificate renewal
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

}

server {
    listen 443 ssl;
    server_name justin.kobo-interns.xyz www.justin.kobo-interns.xyz;

    ssl_certificate /etc/letsencrypt/live/justin.kobo-interns.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/justin.kobo-interns.xyz/privkey.pem;

    # Strong SSL Confirguration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    
    location / {
        proxy_pass http://justin-node:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
